-- Migration 018: Expand Breed Encyclopedia — add 20 more popular UK breeds
-- using Kennel Club and breed club data.

INSERT INTO public.breeds (
  name, slug, group_name, size, popularity_rank, is_popular,
  description, temperament, lifespan, exercise_needs, grooming,
  health_issues, origin, image_url,
  male_height, female_height, male_weight, female_weight,
  coat_type, good_with_children, good_with_other_dogs
)
VALUES
(
  'Cockapoo', 'cockapoo', 'Gundog', 'small', 16, true,
  'The Cockapoo is one of the UK''s most popular designer crossbreeds, a charming mix of Cocker Spaniel and Poodle. Known for their friendly, affectionate nature and low-shedding coat, they make excellent family companions. They are intelligent, easy to train, and adapt well to various living situations.',
  'Friendly, affectionate, intelligent, playful, gentle',
  '13–16 years',
  'Moderate — 45–60 minutes daily. They enjoy walks, playtime, and mental stimulation. Adaptable to owner lifestyle but should not be under-exercised.',
  'Moderate to high — regular brushing needed to prevent matting of the wavy/curly coat. Professional grooming every 6–8 weeks recommended.',
  'Hip dysplasia, progressive retinal atrophy (PRA), ear infections, patellar luxation, allergies',
  'United States (developed in the 1960s)',
  'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9205?w=800&q=80',
  '25–38 cm', '25–38 cm', '5.4–11 kg', '5.4–11 kg',
  'Wavy or curly, low-shedding', true, true
),
(
  'Cavalier King Charles Spaniel', 'cavalier-king-charles-spaniel', 'Toy', 'small', 17, true,
  'The Cavalier King Charles Spaniel is a graceful, affectionate toy breed that thrives on human companionship. Named after King Charles II, they are known for their gentle nature, beautiful silky coat, and expressive eyes. They are equally happy on a sofa or a country walk.',
  'Affectionate, gentle, friendly, playful, adaptable',
  '9–14 years',
  'Moderate — 45–60 minutes daily. They enjoy walks and off-lead play but are not overly demanding. Happy to adapt to their owner''s pace.',
  'Moderate — brushing 3–4 times per week to prevent tangles in the silky coat. Feathering on ears, legs and tail needs attention.',
  'Mitral valve disease (MVD — very common), syringomyelia (SM), hip dysplasia, patellar luxation, eye conditions',
  'United Kingdom (England)',
  'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=800&q=80',
  '30–33 cm', '30–33 cm', '5.9–8.2 kg', '5.9–8.2 kg',
  'Medium-length, silky, feathered', true, true
),
(
  'English Springer Spaniel', 'english-springer-spaniel', 'Gundog', 'medium', 18, true,
  'The English Springer Spaniel is a lively, medium-sized gundog and one of the oldest spaniel breeds. They are energetic, intelligent working dogs that excel in the field and as family pets. Their name comes from their ability to "spring" game.',
  'Friendly, eager-to-please, intelligent, energetic, attentive',
  '12–14 years',
  'High — 1.5–2 hours daily. They are working dogs that need plenty of exercise, mental stimulation, and ideally opportunities to use their natural retrieving and scenting instincts.',
  'Moderate to high — regular brushing needed, especially the feathered ears, chest, legs and tail. Professional grooming every 6–8 weeks.',
  'Hip dysplasia, elbow dysplasia, progressive retinal atrophy (PRA), ear infections, phosphofructokinase deficiency (PFK)',
  'United Kingdom (England)',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '48–51 cm', '46–48 cm', '20–25 kg', '18–23 kg',
  'Medium-length, flat or wavy, feathered', true, true
),
(
  'Yorkshire Terrier', 'yorkshire-terrier', 'Terrier', 'small', 19, true,
  'The Yorkshire Terrier, or "Yorkie," is a small terrier with a big personality. Originally bred in Yorkshire for catching rats in mills, they are now popular companion dogs. Despite their tiny size, they retain typical terrier confidence and spirit. Their fine, silky coat is similar to human hair.',
  'Bold, intelligent, independent, affectionate, sometimes territorial',
  '13–16 years',
  'Moderate — 30–45 minutes daily. Short walks and indoor play suit them well. They have surprising energy for their size but tire easily.',
  'Very high if coat kept long — daily brushing required. Many owners opt for a shorter "puppy cut" to reduce maintenance.',
  'Patellar luxation, tracheal collapse, dental disease, progressive retinal atrophy (PRA), portosystemic shunt',
  'United Kingdom (Yorkshire, England)',
  'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80',
  '18–23 cm', '18–23 cm', '3.2–3.6 kg', '3.2–3.6 kg',
  'Long, silky, straight, single coat', true, false
),
(
  'Pomeranian', 'pomeranian', 'Toy', 'small', 20, true,
  'The Pomeranian is a tiny toy breed with a huge personality and an abundant fluffy double coat. Descended from large Arctic sled dogs, they are surprisingly bold and confident. They are intelligent, alert, and make excellent watchdogs despite their diminutive size.',
  'Bold, curious, lively, intelligent, vocal',
  '12–16 years',
  'Low to moderate — 20–30 minutes daily. Short walks and indoor play suffice. They are active indoors but can overheat due to their thick coat.',
  'High — daily brushing essential to prevent matting of the thick double coat. Regular bathing and professional grooming recommended.',
  'Patellar luxation, tracheal collapse, dental disease, alopecia X (black skin disease), hypothyroidism',
  'Germany / Poland (Pomerania region)',
  'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80',
  '18–30 cm', '18–30 cm', '1.4–3.2 kg', '1.4–3.2 kg',
  'Long, fluffy, dense double coat', true, false
),
(
  'Jack Russell Terrier', 'jack-russell-terrier', 'Terrier', 'small', 21, true,
  'The Jack Russell Terrier is a small, energetic working terrier originally bred for fox hunting. They are fearless, intelligent, and bursting with energy. They need an active owner who can provide plenty of exercise and mental challenges. Not suited to a sedentary lifestyle.',
  'Fearless, intelligent, energetic, stubborn, loyal',
  '13–16 years',
  'Very high — 1.5–2 hours daily. They need running, chasing, digging, and problem-solving. A bored Jack Russell will find their own (usually destructive) entertainment.',
  'Low — occasional brushing. Smooth coats need minimal care; rough/broken coats may need hand-stripping.',
  'Patellar luxation, lens luxation, ataxia, deafness, Legg-Calvé-Perthes disease',
  'United Kingdom (England)',
  'https://images.unsplash.com/photo-1591769225440-811ad7d6eca6?w=800&q=80',
  '25–30 cm', '25–30 cm', '6–8 kg', '6–8 kg',
  'Smooth, rough, or broken coat', true, false
),
(
  'Rottweiler', 'rottweiler', 'Working', 'large', 22, true,
  'The Rottweiler is a powerful, confident working breed with a long history as a drover, guard dog, and police dog. They are loyal, calm, and courageous with their family but naturally aloof with strangers. They need early socialisation, consistent training, and an experienced owner.',
  'Confident, calm, courageous, loyal, aloof with strangers',
  '8–10 years',
  'High — 1.5–2 hours daily. They need walks, play, and mental stimulation. Weight-bearing exercise should be limited until fully grown to protect joints.',
  'Low — weekly brushing. They shed seasonally. Minimal grooming needs despite the dense coat.',
  'Hip and elbow dysplasia, osteosarcoma (bone cancer), bloat, subaortic stenosis, entropion',
  'Germany (Rottweil)',
  'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800&q=80',
  '61–69 cm', '56–63 cm', '50–60 kg', '35–48 kg',
  'Short, dense, flat-lying double coat', true, false
),
(
  'Dobermann', 'dobermann', 'Working', 'large', 23, true,
  'The Dobermann is an elegant, powerful, and highly intelligent working breed developed in Germany as a personal protection dog. They are loyal, alert, and trainable. With proper socialisation, they make devoted family companions. They are often used in police, military, and search-and-rescue roles.',
  'Loyal, alert, intelligent, fearless, obedient',
  '10–13 years',
  'High — 1.5–2 hours daily. They need vigorous exercise including running and mental challenges. They excel at obedience, agility, and protection sports.',
  'Low — weekly brushing. Minimal grooming. Their short coat is easy to maintain.',
  'Dilated cardiomyopathy (DCM — very common), von Willebrand disease, cervical spondylomyelopathy (Wobbler syndrome), hip dysplasia, bloat',
  'Germany',
  'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800&q=80',
  '68–72 cm', '63–68 cm', '40–45 kg', '32–35 kg',
  'Short, smooth, close-fitting', true, false
),
(
  'Siberian Husky', 'siberian-husky', 'Working', 'medium', 24, true,
  'The Siberian Husky is a medium-sized working dog bred for pulling sleds in harsh Arctic conditions. They are known for their striking appearance, piercing eyes, and incredible endurance. They are friendly, outgoing, and notoriously independent — not a breed for the first-time dog owner.',
  'Friendly, outgoing, alert, gentle, independent, stubborn',
  '12–14 years',
  'Very high — 2+ hours daily. They need running, hiking, or sledding. A securely fenced garden is essential as they are expert escape artists. Mental stimulation is crucial.',
  'Moderate — weekly brushing, daily during seasonal shedding (twice yearly heavy "blowouts").',
  'Hip dysplasia, eye conditions (cataracts, PRA), hypothyroidism, zinc-responsive dermatosis',
  'Siberia, Russia',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '53–60 cm', '50–56 cm', '20–27 kg', '16–23 kg',
  'Medium-length, dense double coat', true, true
),
(
  'Great Dane', 'great-dane', 'Working', 'giant', 25, true,
  'The Great Dane is a giant breed known as the "Apollo of Dogs" for its noble appearance and imposing size. Despite their stature, they are gentle, affectionate, and patient — often called "gentle giants." They need plenty of space and are not suited to small homes.',
  'Friendly, patient, dependable, gentle, courageous',
  '8–10 years',
  'Moderate — 1–1.5 hours daily. Short walks due to joint concerns. Avoid high-impact exercise until fully grown (around 2 years).',
  'Low — weekly brushing. Minimal grooming. Their short coat is easy to maintain.',
  'Hip dysplasia, bloat (very high risk), dilated cardiomyopathy, hypothyroidism, wobbler syndrome, bone cancer',
  'Germany',
  'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800&q=80',
  '76–86 cm', '71–81 cm', '54–90 kg', '45–59 kg',
  'Short, smooth, close-fitting', true, true
),
(
  'Pug', 'pug', 'Toy', 'small', 26, true,
  'The Pug is a charming, comical toy breed with a wrinkled face and curled tail. They are one of the oldest dog breeds, dating back to ancient China. Pugs are known for their sociable, loving nature and their desire to be the centre of attention. They are ideal companion dogs.',
  'Charming, mischievous, loving, stubborn, sociable',
  '13–15 years',
  'Low — 20–30 minutes daily. Short walks due to brachycephalic breathing. Avoid heat and overexertion. They are prone to obesity.',
  'Low — weekly brushing. Wrinkle folds need cleaning to prevent infection. Minimal shedding for a double-coated breed.',
  'Brachycephalic airway syndrome, eye problems (proptosis, corneal ulcers), hip dysplasia, Pug dog encephalitis (PDE), skin fold dermatitis, obesity',
  'China',
  'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80',
  '25–30 cm', '25–30 cm', '6.3–8.1 kg', '6.3–8.1 kg',
  'Short, smooth, double coat', true, true
),
(
  'Bernese Mountain Dog', 'bernese-mountain-dog', 'Working', 'giant', 27, true,
  'The Bernese Mountain Dog is a striking tri-coloured giant breed from the Swiss Alps. They were originally farm dogs used for drafting and herding. They are gentle, calm, and affectionate with their family. Their beautiful coat requires regular maintenance.',
  'Gentle, calm, affectionate, loyal, good-natured',
  '7–10 years',
  'Moderate — 1 hour daily. They enjoy walks and cooler weather. Avoid overexertion in heat due to their thick coat.',
  'High — daily brushing during shedding seasons. Their thick double coat sheds heavily twice yearly.',
  'Hip and elbow dysplasia, histiocytic sarcoma (cancer), bloat, progressive retinal atrophy (PRA), von Willebrand disease',
  'Switzerland',
  'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800&q=80',
  '64–70 cm', '58–66 cm', '36–48 kg', '34–44 kg',
  'Long, silky, tri-coloured double coat', true, true
),
(
  'Dalmatian', 'dalmatian', 'Utility', 'large', 28, true,
  'The Dalmatian is instantly recognisable by its distinctive white coat with black or liver spots. They are energetic, intelligent dogs with a long history as carriage dogs and firehouse mascots. They need plenty of exercise and mental stimulation to be happy companions.',
  'Outgoing, energetic, intelligent, sensitive, playful',
  '10–13 years',
  'High — 1.5–2 hours daily. They are bred for endurance and need running, long walks, or canine sports. Without enough exercise they can become destructive.',
  'Low — weekly brushing. They shed year-round. Their short coat is easy to maintain.',
  'Deafness (congenital — test puppies), urinary stones (urate), hip dysplasia, allergies, thyroid issues',
  'Croatia (Dalmatia region)',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '58–61 cm', '56–58 cm', '27–32 kg', '24–29 kg',
  'Short, smooth, dense', true, true
),
(
  'West Highland White Terrier', 'west-highland-white-terrier', 'Terrier', 'small', 29, true,
  'The West Highland White Terrier, or "Westie," is a small, sturdy terrier with a distinctive white coat and spirited personality. Originally bred for hunting vermin in Scotland, they are confident, independent, and full of character. They make loyal companions for those who appreciate terrier spirit.',
  'Confident, independent, friendly, stubborn, alert',
  '12–16 years',
  'Moderate — 45–60 minutes daily. They enjoy walks and play. Their terrier instincts mean they love to dig and explore.',
  'Moderate to high — daily brushing recommended. Their harsh double coat needs regular stripping or clipping every 6–8 weeks.',
  'Patellar luxation, craniomandibular osteopathy (CMO), skin allergies (atopy), Legg-Calvé-Perthes disease, copper toxicosis',
  'United Kingdom (Scotland)',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '25–28 cm', '25–28 cm', '7–10 kg', '6–7 kg',
  'Double coat — harsh outer, soft undercoat', true, false
),
(
  'Bichon Frise', 'bichon-frise', 'Toy', 'small', 30, true,
  'The Bichon Frise is a small, cheerful toy breed with a fluffy white coat and a playful, affectionate personality. They are known for their hypoallergenic coat and their ability to get along with everyone. They thrive on companionship and do not like being left alone.',
  'Cheerful, affectionate, playful, gentle, sensitive',
  '12–15 years',
  'Moderate — 30–45 minutes daily. Short walks and play sessions. They are active indoors and enjoy games.',
  'Very high — professional grooming every 4–6 weeks is essential. Daily brushing at home to prevent matting of the dense curly coat.',
  'Patellar luxation, bladder stones, allergies, dental disease, cataracts, liver shunt',
  'Mediterranean (popularised in France)',
  'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80',
  '23–30 cm', '23–30 cm', '3–5 kg', '3–5 kg',
  'Dense, curly, hypoallergenic', true, true
),
(
  'Hungarian Vizsla', 'hungarian-vizsla', 'Gundog', 'large', 31, true,
  'The Hungarian Vizsla is a sleek, athletic gundog known for its striking rust-coloured coat and affectionate "velcro" personality. They form incredibly strong bonds with their owners and are often called "velcro dogs" for their desire to be close. They need an active lifestyle.',
  'Affectionate, energetic, gentle, sensitive, intelligent',
  '12–14 years',
  'Very high — 2+ hours daily. They need running, retrieving, and mental challenges. They excel at agility, field trials, and canicross. A bored Vizsla becomes anxious and destructive.',
  'Low — weekly brushing. Minimal grooming. Their short coat is easy to maintain.',
  'Hip dysplasia, epilepsy, hypothyroidism, progressive retinal atrophy (PRA), cancer (lymphosarcoma)',
  'Hungary',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '56–61 cm', '53–58 cm', '20–30 kg', '18–25 kg',
  'Short, smooth, dense', true, true
),
(
  'Weimaraner', 'weimaraner', 'Gundog', 'large', 32, true,
  'The Weimaraner is a sleek, athletic gundog known for its distinctive silver-grey coat and piercing eyes. Originally bred for hunting large game in Germany, they are intelligent, energetic, and deeply attached to their owners. They are not suited to being left alone for long periods.',
  'Friendly, fearless, alert, obedient, high-energy',
  '11–14 years',
  'Very high — 2+ hours daily. They need vigorous exercise, running, and mental stimulation. Without it they become anxious and destructive.',
  'Low — weekly brushing. Minimal grooming. Their short coat is easy to maintain.',
  'Hip dysplasia, bloat, von Willebrand disease, distichiasis, hypothyroidism, skin allergies',
  'Germany',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '59–70 cm', '57–65 cm', '30–40 kg', '25–35 kg',
  'Short, smooth, sleek', true, true
),
(
  'Rhodesian Ridgeback', 'rhodesian-ridgeback', 'Hound', 'large', 33, true,
  'The Rhodesian Ridgeback is a large, muscular hound originally bred in South Africa for hunting lions. They are known for the distinctive ridge of hair along their spine that grows in the opposite direction. They are dignified, loyal, and protective of their family.',
  'Dignified, loyal, protective, intelligent, independent',
  '10–12 years',
  'High — 1.5–2 hours daily. They need walks, runs, and mental stimulation. They are athletic dogs that enjoy having a job to do.',
  'Low — weekly brushing. Minimal grooming. Their short coat is easy to maintain.',
  'Hip dysplasia, dermoid sinus, hypothyroidism, elbow dysplasia, degenerative myelopathy',
  'South Africa / Zimbabwe (Rhodesia)',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '63–69 cm', '61–66 cm', '36–41 kg', '29–34 kg',
  'Short, dense, sleek', true, false
),
(
  'Newfoundland', 'newfoundland', 'Working', 'giant', 34, true,
  'The Newfoundland is a giant, powerful working breed from Canada known for its exceptional swimming ability and gentle temperament. They are famous for water rescue and their natural lifesaving instincts. Despite their size, they are patient, gentle, and excellent with children.',
  'Gentle, patient, sweet-natured, protective, trainable',
  '9–10 years',
  'Moderate — 1 hour daily. They enjoy swimming above all else. Short walks and water exercise are ideal. They can overheat due to their thick coat.',
  'High — daily brushing during shedding seasons. Their thick double coat sheds heavily twice yearly.',
  'Hip and elbow dysplasia, subaortic stenosis (SAS), cystinuria (stones), bloat, ectropion',
  'Canada (Newfoundland)',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '69–74 cm', '63–69 cm', '60–70 kg', '45–55 kg',
  'Thick, oily, water-resistant double coat', true, true
),
(
  'Old English Sheepdog', 'old-english-sheepdog', 'Pastoral', 'large', 35, true,
  'The Old English Sheepdog is a large, shaggy pastoral breed with a distinctive bear-like gait and abundant coat. They are gentle, adaptable, and make excellent family companions. Their iconic appearance requires significant grooming commitment.',
  'Gentle, adaptable, sociable, intelligent, playful',
  '10–12 years',
  'Moderate — 1–1.5 hours daily. They enjoy walks and play. Despite their size they are fairly easy-going but still need regular exercise.',
  'Very high — daily brushing to prevent matting. Professional grooming every 6–8 weeks. Their coat can be kept in a shorter clip to reduce maintenance.',
  'Hip dysplasia, progressive retinal atrophy (PRA), cataracts, hypothyroidism, deafness',
  'United Kingdom (England)',
  'https://images.unsplash.com/photo-1606567595334-d39972c85ede?w=800&q=80',
  '61 cm+', '56 cm+', '36–46 kg', '30–40 kg',
  'Long, shaggy, thick double coat', true, true
)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug,
  group_name = EXCLUDED.group_name,
  size = EXCLUDED.size,
  popularity_rank = EXCLUDED.popularity_rank,
  is_popular = EXCLUDED.is_popular,
  description = EXCLUDED.description,
  temperament = EXCLUDED.temperament,
  lifespan = EXCLUDED.lifespan,
  exercise_needs = EXCLUDED.exercise_needs,
  grooming = EXCLUDED.grooming,
  health_issues = EXCLUDED.health_issues,
  origin = EXCLUDED.origin,
  image_url = EXCLUDED.image_url,
  male_height = EXCLUDED.male_height,
  female_height = EXCLUDED.female_height,
  male_weight = EXCLUDED.male_weight,
  female_weight = EXCLUDED.female_weight,
  coat_type = EXCLUDED.coat_type,
  good_with_children = EXCLUDED.good_with_children,
  good_with_other_dogs = EXCLUDED.good_with_other_dogs;
