-- Migration 022: Fixes for claims, auth, verification redirect, and more breeds

-- ============================================================================
-- 1. FIX CLAIM APPROVAL — add missing columns
-- ============================================================================
ALTER TABLE public.claims
  ADD COLUMN IF NOT EXISTS admin_notes text,
  ADD COLUMN IF NOT EXISTS status_update_sent_at timestamptz;

-- ============================================================================
-- 2. ADD MANY MORE BREEDS FOR ALL ANIMAL TYPES
-- ============================================================================

-- MORE CATS
INSERT INTO public.breeds (name, slug, animal_type, group_name, size, popularity_rank, is_popular, description, temperament, lifespan, exercise_needs, grooming, health_issues, origin, image_url, male_height, female_height, male_weight, female_weight, coat_type, good_with_children, good_with_other_dogs)
VALUES
('Norwegian Forest Cat', 'norwegian-forest-cat', 'cat', 'Longhair', 'large', 42, true, 'The Norwegian Forest Cat is a large, rugged breed built for harsh Scandinavian winters. They are athletic climbers with a thick water-resistant coat and a gentle, independent nature.', 'Independent, gentle, athletic, intelligent, friendly', '14–16 years', 'Moderate — 30–60 minutes daily. They love climbing trees and high places.', 'High — weekly brushing, daily during shedding seasons. Thick double coat.', 'Hypertrophic cardiomyopathy (HCM), glycogen storage disease type IV, hip dysplasia', 'Norway', 'https://images.unsplash.com/photo-1517331156700-0c3d5f07f25e?w=800&q=80', '25–30 cm', '25–30 cm', '5.5–7.5 kg', '4–6 kg', 'Long, thick, water-resistant double coat', true, true),
('Russian Blue', 'russian-blue', 'cat', 'Shorthair', 'medium', 43, true, 'The Russian Blue is an elegant cat with a silvery-blue coat and emerald-green eyes. They are shy with strangers but deeply loyal and affectionate with their chosen family.', 'Shy, loyal, gentle, intelligent, quiet', '15–20 years', 'Moderate — 30–45 minutes daily. They enjoy play but are not overly demanding.', 'Low — weekly brushing. Short, dense coat sheds minimally.', 'Hypertrophic cardiomyopathy (HCM), bladder stones, obesity', 'Russia (Archangel Isles)', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&q=80', '25–30 cm', '25–30 cm', '4.5–6 kg', '3–4.5 kg', 'Short, dense, silvery-blue double coat', true, true),
('Abyssinian', 'abyssinian', 'cat', 'Shorthair', 'medium', 44, true, 'The Abyssinian is one of the oldest cat breeds, known for its ticked coat and boundless energy. They are constantly on the move and need an active household.', 'Active, curious, playful, intelligent, affectionate', '12–15 years', 'High — 60+ minutes daily. They need climbing, interactive toys, and mental stimulation.', 'Low — weekly brushing. Short coat is easy to maintain.', 'Pyruvate kinase deficiency, progressive retinal atrophy (PRA), renal amyloidosis', 'Ethiopia (Abyssinia)', 'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=800&q=80', '20–25 cm', '20–25 cm', '4–5 kg', '3–4 kg', 'Short, ticked (agouti) coat — ruddy, red, blue, fawn', true, true),
('Burmese', 'burmese', 'cat', 'Shorthair', 'medium', 45, true, 'The Burmese is a people-oriented cat that thrives on companionship. They are muscular, playful, and known for following their owners from room to room like a puppy.', 'Affectionate, playful, vocal, intelligent, social', '16–18 years', 'Moderate — 45–60 minutes daily. They enjoy interactive play and climbing.', 'Low — weekly brushing. Short, satin-like coat is easy to maintain.', 'Hypokalaemia, craniofacial defect (in some lines), diabetes mellitus', 'Myanmar (Burma) / Thailand', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&q=80', '25–30 cm', '25–30 cm', '4–6 kg', '3–4.5 kg', 'Short, glossy, satin-like — sable, champagne, blue, platinum', true, true),
('Exotic Shorthair', 'exotic-shorthair', 'cat', 'Shorthair', 'medium', 46, true, 'The Exotic Shorthair is essentially a short-haired Persian. They share the Persian sweet temperament and flat face but with a plush, easy-care coat.', 'Sweet, calm, affectionate, quiet, loyal', '12–15 years', 'Low — 20–30 minutes daily. Short play sessions. They prefer lounging.', 'Low — weekly brushing. Short, dense coat is much easier than Persian.', 'Polycystic kidney disease (PKD), brachycephalic issues, tear staining, dental malocclusion', 'United States', 'https://images.unsplash.com/photo-1517331156700-0c3d5f07f25e?w=800&q=80', '25–30 cm', '25–30 cm', '3.5–6 kg', '3–5 kg', 'Short, dense, plush double coat', true, true),
('Oriental Shorthair', 'oriental-shorthair', 'cat', 'Shorthair', 'medium', 47, true, 'The Oriental Shorthair is a sleek, elegant cat closely related to the Siamese. They are vocal, intelligent, and form deep bonds with their owners.', 'Vocal, intelligent, affectionate, demanding, active', '12–15 years', 'High — 45–60 minutes daily. They need climbing, play, and mental stimulation.', 'Low — weekly brushing. Short coat is easy to maintain.', 'Progressive retinal atrophy (PRA), amyloidosis, asthma, dental issues', 'Thailand / United Kingdom', 'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=800&q=80', '20–25 cm', '20–25 cm', '3.5–5.5 kg', '3–4.5 kg', 'Short, sleek — many colours and patterns', true, true),
('Turkish Van', 'turkish-van', 'cat', 'Semi-longhair', 'large', 48, true, 'The Turkish Van is a rare breed famous for its love of water and distinctive Van pattern. They are active, intelligent, and strong swimmers.', 'Active, intelligent, independent, vocal, water-loving', '12–17 years', 'High — 60+ minutes daily. They love water play, climbing, and exploring.', 'Moderate — weekly brushing. Semi-long coat with no undercoat (low matting).', 'Hypertrophic cardiomyopathy (HCM), deafness (in some white lines)', 'Turkey (Lake Van region)', 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800&q=80', '25–30 cm', '25–30 cm', '5–7.5 kg', '4–6 kg', 'Semi-long, cashmere-like, water-resistant — white with coloured head and tail', true, true)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug, animal_type = EXCLUDED.animal_type, group_name = EXCLUDED.group_name, size = EXCLUDED.size,
  popularity_rank = EXCLUDED.popularity_rank, is_popular = EXCLUDED.is_popular, description = EXCLUDED.description,
  temperament = EXCLUDED.temperament, lifespan = EXCLUDED.lifespan, exercise_needs = EXCLUDED.exercise_needs,
  grooming = EXCLUDED.grooming, health_issues = EXCLUDED.health_issues, origin = EXCLUDED.origin,
  image_url = EXCLUDED.image_url, male_height = EXCLUDED.male_height, female_height = EXCLUDED.female_height,
  male_weight = EXCLUDED.male_weight, female_weight = EXCLUDED.female_weight, coat_type = EXCLUDED.coat_type,
  good_with_children = EXCLUDED.good_with_children, good_with_other_dogs = EXCLUDED.good_with_other_dogs;

-- MORE BIRDS
INSERT INTO public.breeds (name, slug, animal_type, group_name, size, popularity_rank, is_popular, description, temperament, lifespan, exercise_needs, grooming, health_issues, origin, image_url, male_height, female_height, male_weight, female_weight, coat_type, good_with_children, good_with_other_dogs)
VALUES
('Conure', 'conure', 'bird', 'Parrot', 'small', 49, true, 'Conures are small to medium parrots known for their playful, affectionate personalities. They are quieter than larger parrots but still need plenty of interaction and out-of-cage time.', 'Playful, affectionate, vocal, active, intelligent', '20–30 years', 'High — minimum 2–3 hours out of cage daily. They need flight space, toys, and social interaction.', 'Moderate — regular nail and beak trimming, bathing, cage cleaning.', 'Respiratory infections, feather plucking, PDD, psittacosis, beak malocclusion', 'Central and South America', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80', '25–38 cm', '25–38 cm', '0.06–0.25 kg', '0.06–0.25 kg', 'Vivid colours — green, yellow, orange, red', true, true),
('Eclectus Parrot', 'eclectus-parrot', 'bird', 'Parrot', 'medium', 50, true, 'The Eclectus Parrot is known for extreme sexual dimorphism — males are bright green, females are vivid red and purple. They are calm, intelligent, and excellent talkers.', 'Calm, intelligent, gentle, excellent talker, sensitive', '30–50 years', 'High — minimum 3 hours out of cage daily. They need space, toys, and mental stimulation.', 'Moderate — regular nail and beak trimming, bathing, cage cleaning.', 'Hypovitaminosis A, feather plucking, PDD, aspergillosis, toe tapping', 'Solomon Islands, New Guinea, Indonesia', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80', '35–42 cm', '35–42 cm', '0.4–0.6 kg', '0.4–0.6 kg', 'Male: bright green. Female: vivid red and purple', true, true),
('Quaker Parrot', 'quaker-parrot', 'bird', 'Parrot', 'small', 51, true, 'The Quaker Parrot, or Monk Parakeet, is a small, intelligent parrot known for building elaborate communal nests. They are excellent talkers and form strong bonds with owners.', 'Social, intelligent, vocal, playful, territorial', '20–30 years', 'High — minimum 2–3 hours out of cage daily. They need flight space and social interaction.', 'Moderate — regular nail and beak trimming, bathing, cage cleaning.', 'Feather plucking, fatty liver disease, respiratory infections, egg binding', 'South America (Argentina, Bolivia, Brazil)', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80', '28–30 cm', '28–30 cm', '0.1 kg', '0.1 kg', 'Green body with grey face and chest', true, true),
('Indian Ringneck Parakeet', 'indian-ringneck-parakeet', 'bird', 'Parrot', 'medium', 52, true, 'The Indian Ringneck Parakeet is a popular pet known for its talking ability and elegant long tail. They are intelligent but can be independent and sometimes aloof.', 'Intelligent, independent, vocal, active, sometimes aloof', '20–30 years', 'High — minimum 2–3 hours out of cage daily. They need flight space and toys.', 'Moderate — regular nail and beak trimming, bathing, cage cleaning.', 'Respiratory infections, feather plucking, PDD, psittacosis, aspergillosis', 'India, Sri Lanka', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80', '40–42 cm', '40–42 cm', '0.12 kg', '0.12 kg', 'Various colours — green, blue, yellow, white, grey', true, false),
('Finch', 'finch', 'bird', 'Songbird', 'small', 53, true, 'Finches are small, active songbirds that are best kept in pairs or small groups. They are relatively low-maintenance and provide beautiful songs and colours.', 'Active, social, independent, vocal, hardy', '4–9 years', 'Moderate — need a spacious cage for flight. They are active and need horizontal flight space.', 'Low — regular cage cleaning, fresh food and water daily.', 'Respiratory infections, mites, egg binding, scaly face mites', 'Worldwide (many species)', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80', '10–15 cm', '10–15 cm', '0.01–0.02 kg', '0.01–0.02 kg', 'Various — zebra, society, gouldian, star', true, true),
('Pionus Parrot', 'pionus-parrot', 'bird', 'Parrot', 'medium', 54, true, 'The Pionus Parrot is a quiet, gentle parrot ideal for apartment living. They are less demanding than larger parrots and rarely scream.', 'Quiet, gentle, reserved, intelligent, affectionate', '25–40 years', 'Moderate — minimum 2 hours out of cage daily. They enjoy interaction but are not overly demanding.', 'Moderate — regular nail and beak trimming, bathing, cage cleaning.', 'Respiratory infections, aspergillosis, vitamin A deficiency, obesity', 'Central and South America', 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80', '25–30 cm', '25–30 cm', '0.2–0.3 kg', '0.2–0.3 kg', 'Blue-headed, bronze-winged, white-capped, dusky', true, true)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug, animal_type = EXCLUDED.animal_type, group_name = EXCLUDED.group_name, size = EXCLUDED.size,
  popularity_rank = EXCLUDED.popularity_rank, is_popular = EXCLUDED.is_popular, description = EXCLUDED.description,
  temperament = EXCLUDED.temperament, lifespan = EXCLUDED.lifespan, exercise_needs = EXCLUDED.exercise_needs,
  grooming = EXCLUDED.grooming, health_issues = EXCLUDED.health_issues, origin = EXCLUDED.origin,
  image_url = EXCLUDED.image_url, male_height = EXCLUDED.male_height, female_height = EXCLUDED.female_height,
  male_weight = EXCLUDED.male_weight, female_weight = EXCLUDED.female_weight, coat_type = EXCLUDED.coat_type,
  good_with_children = EXCLUDED.good_with_children, good_with_other_dogs = EXCLUDED.good_with_other_dogs;

-- MORE FISH
INSERT INTO public.breeds (name, slug, animal_type, group_name, size, popularity_rank, is_popular, description, temperament, lifespan, exercise_needs, grooming, health_issues, origin, image_url, male_height, female_height, male_weight, female_weight, coat_type, good_with_children, good_with_other_dogs)
VALUES
('Molly', 'molly', 'fish', 'Livebearer', 'small', 55, true, 'The Molly is a popular livebearing fish that comes in many colours and fin types. They are hardy, peaceful, and ideal for community tanks.', 'Peaceful, active, social, hardy, prolific breeder', '3–5 years', 'Requires minimum 40 litres. They need plants and open swimming space.', 'Low — regular water changes and filter maintenance. They tolerate various conditions.', 'Ich, fin rot, dropsy, poor water quality, constipation', 'Central America', 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=800&q=80', '5–10 cm', '5–10 cm', '0.005 kg', '0.005 kg', 'Various colours — black, gold, white, dalmatian', true, true),
('Platy', 'platy', 'fish', 'Livebearer', 'small', 56, true, 'The Platy is a colourful, easy-going livebearer perfect for beginners. They are peaceful, hardy, and breed readily in community tanks.', 'Peaceful, active, hardy, social, easygoing', '3–5 years', 'Requires minimum 40 litres. They need plants for hiding and open swimming space.', 'Low — regular water changes and filter maintenance.', 'Ich, fin rot, dropsy, poor water quality, tuberculosis', 'Central America', 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=800&q=80', '4–7 cm', '4–7 cm', '0.003 kg', '0.003 kg', 'Red, orange, yellow, blue, wagtail, tuxedo', true, true),
('Swordtail', 'swordtail', 'fish', 'Livebearer', 'small', 57, true, 'The Swordtail is named for the long lower tail fin of males. They are active, colourful livebearers that add movement to community tanks.', 'Active, peaceful, hardy, social, fast swimmer', '3–5 years', 'Requires minimum 60 litres. They are active swimmers needing open space.', 'Low — regular water changes and filter maintenance.', 'Ich, fin rot, dropsy, poor water quality, constipation', 'Central America', 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=800&q=80', '8–14 cm', '8–14 cm', '0.005 kg', '0.005 kg', 'Red, green, pineapple, marigold, various', true, true),
('Corydoras Catfish', 'corydoras-catfish', 'fish', 'Catfish', 'small', 58, true, 'Corydoras are small, peaceful bottom-dwelling catfish that clean the substrate. They are social and should be kept in groups of 6 or more.', 'Peaceful, social, active (bottom), hardy, entertaining', '5–10 years', 'Requires minimum 40 litres for a group of 6. They need soft substrate to protect their barbels.', 'Low — regular water changes. They help keep the bottom clean.', 'Barbel infections, ich, poor water quality, rough substrate injuries', 'South America', 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=800&q=80', '3–7 cm', '3–7 cm', '0.001–0.005 kg', '0.001–0.005 kg', 'Armoured body with barbels — bronze, albino, panda, sterbai', true, true),
('Cherry Barb', 'cherry-barb', 'fish', 'Cyprinid', 'small', 59, true, 'The Cherry Barb is a small, peaceful cyprinid known for the males vivid red colour during breeding. They are excellent community fish.', 'Peaceful, shy, active, schooling, hardy', '4–7 years', 'Requires minimum 40 litres for a school of 6. They need plants and open swimming space.', 'Low — regular water changes and filter maintenance.', 'Ich, fin rot, dropsy, poor water quality', 'Sri Lanka', 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=800&q=80', '3–5 cm', '3–5 cm', '0.001 kg', '0.001 kg', 'Male: vivid red. Female: duller with lateral stripe', true, true),
('Rainbowfish', 'rainbowfish', 'fish', 'Rainbowfish', 'medium', 60, true, 'Rainbowfish are stunning freshwater fish known for their iridescent colours that intensify with age. They are peaceful schooling fish that bring life to any aquarium.', 'Peaceful, active, schooling, hardy, colourful', '5–8 years', 'Requires minimum 100 litres for a school of 6. They need open swimming space and plants.', 'Moderate — regular water changes. They prefer clean, well-oxygenated water.', 'Ich, fin rot, bacterial infections, poor water quality', 'Australia, New Guinea, Indonesia', 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=800&q=80', '8–15 cm', '8–15 cm', '0.005–0.05 kg', '0.005–0.05 kg', 'Iridescent — blue, red, yellow, silver', true, true),
('Tang Fish', 'tang-fish', 'fish', 'Surgeonfish', 'medium', 61, true, 'Tangs, or Surgeonfish, are popular marine fish known for their laterally compressed bodies and scalpel-like spines near the tail. They are active algae grazers.', 'Active, territorial, hardy, algae grazer, fast swimmer', '8–20 years', 'Requires large marine tank — minimum 200 litres. They need plenty of swimming space and live rock.', 'Moderate — marine tank maintenance. Stable water parameters essential.', 'Marine ich, lateral line erosion, velvet, aggression-related injuries', 'Indo-Pacific', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', '15–40 cm', '15–40 cm', '0.1–0.8 kg', '0.1–0.8 kg', 'Blue, yellow, purple, surgeonfish shape', true, false),
('Mandarin Fish', 'mandarin-fish', 'fish', 'Dragonet', 'small', 62, true, 'The Mandarin Fish is one of the most beautiful saltwater fish, covered in psychedelic patterns of blue, green, orange and red. They are shy and need a mature reef tank.', 'Shy, slow-moving, picky eater, peaceful, nocturnal', '10–15 years', 'Requires mature reef tank — minimum 100 litres. They need live rock with copepods.', 'Moderate — marine tank maintenance. They need a steady supply of live copepods.', 'Starvation (picky eaters), marine ich, poor water quality', 'Pacific Ocean (Philippines, Indonesia, Australia)', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', '6–7 cm', '6–7 cm', '0.003 kg', '0.003 kg', 'Psychedelic patterns — blue, green, orange, red spots', true, true)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug, animal_type = EXCLUDED.animal_type, group_name = EXCLUDED.group_name, size = EXCLUDED.size,
  popularity_rank = EXCLUDED.popularity_rank, is_popular = EXCLUDED.is_popular, description = EXCLUDED.description,
  temperament = EXCLUDED.temperament, lifespan = EXCLUDED.lifespan, exercise_needs = EXCLUDED.exercise_needs,
  grooming = EXCLUDED.grooming, health_issues = EXCLUDED.health_issues, origin = EXCLUDED.origin,
  image_url = EXCLUDED.image_url, male_height = EXCLUDED.male_height, female_height = EXCLUDED.female_height,
  male_weight = EXCLUDED.male_weight, female_weight = EXCLUDED.female_weight, coat_type = EXCLUDED.coat_type,
  good_with_children = EXCLUDED.good_with_children, good_with_other_dogs = EXCLUDED.good_with_other_dogs;

-- MORE REPTILES
INSERT INTO public.breeds (name, slug, animal_type, group_name, size, popularity_rank, is_popular, description, temperament, lifespan, exercise_needs, grooming, health_issues, origin, image_url, male_height, female_height, male_weight, female_weight, coat_type, good_with_children, good_with_other_dogs)
VALUES
('Red-Eared Slider', 'red-eared-slider', 'reptile', 'Turtle', 'medium', 63, true, 'The Red-Eared Slider is one of the most popular pet turtles. They are aquatic, active, and need both water and basking areas to thrive.', 'Active, hardy, aquatic, basking, long-lived', '20–30 years', 'Requires large tank — minimum 150 litres for juveniles, 300+ litres for adults. They need a basking area and UVB lighting.', 'High — excellent filtration essential. Regular water changes. Basking area cleaning.', 'Shell rot, respiratory infections, vitamin A deficiency, metabolic bone disease', 'United States (southern)', 'https://images.unsplash.com/photo-1504450874802-0ed58ffa9b64?w=800&q=80', '15–30 cm', '15–30 cm', '1–3 kg', '1–3 kg', 'Smooth shell with red stripe behind eye — green, brown, yellow', true, true),
('Blue-Tongued Skink', 'blue-tongued-skink', 'reptile', 'Skink', 'medium', 64, true, 'The Blue-Tongued Skink is a large, docile lizard with a distinctive blue tongue used as a defence mechanism. They are easy to care for and enjoy handling.', 'Docile, slow-moving, hardy, tolerant, friendly', '15–20 years', 'Requires minimum 120 cm vivarium. They need hiding spots, a basking area, and space to explore.', 'Low — regular enclosure cleaning, UVB lighting replacement, nail trimming.', 'Metabolic bone disease, obesity, respiratory infections, scale rot', 'Australia, Indonesia, New Guinea', 'https://images.unsplash.com/photo-1504450874802-0ed58ffa9b64?w=800&q=80', '40–60 cm', '40–60 cm', '0.3–0.7 kg', '0.3–0.7 kg', 'Smooth scales — tan, grey, brown with bands', true, true),
('Royal Python', 'royal-python', 'reptile', 'Snake', 'medium', 65, true, 'The Royal Python is another name for the Ball Python. Docile, manageable size, and popular for beginners.', 'Docile, shy, nocturnal, hardy, tolerant', '20–30 years', 'Requires minimum 90 cm vivarium. Hiding spots, water bowl, climbing branches.', 'Low — enclosure cleaning, humidity monitoring, shedding assistance.', 'Respiratory infections, mites, scale rot, mouth rot, inclusion body disease', 'West and Central Africa', 'https://images.unsplash.com/photo-1531386816498-118b97284d01?w=800&q=80', '90–120 cm', '90–120 cm', '1–1.5 kg', '1–1.5 kg', 'Smooth scales — normal, pastel, albino, piebald', true, true),
('Veiled Chameleon', 'veiled-chameleon', 'reptile', 'Chameleon', 'medium', 66, true, 'The Veiled Chameleon is a striking arboreal lizard with a tall casque on its head. They are fascinating to watch but not for handling due to stress sensitivity.', 'Shy, territorial, stress-sensitive, fascinating, arboreal', '5–8 years', 'Requires tall screen vivarium — minimum 60x60x120 cm. They need vertical climbing space, plants, and misting.', 'Moderate — daily misting, regular enclosure cleaning, UVB lighting, gut-loading feeder insects.', 'Metabolic bone disease, respiratory infections, dehydration, egg binding, stress-related illness', 'Yemen, Saudi Arabia', 'https://images.unsplash.com/photo-1504450874802-0ed58ffa9b64?w=800&q=80', '35–60 cm', '35–60 cm', '0.1–0.2 kg', '0.1–0.2 kg', 'Colour-changing skin — green, yellow, blue, stripes', false, false),
('Uromastyx', 'uromastyx', 'reptile', 'Lizard', 'medium', 67, true, 'The Uromastyx, or Spiny-Tailed Lizard, is a desert-dwelling herbivore known for its spiny tail and bright colours. They are active during the day and enjoy basking.', 'Diurnal, active, hardy, herbivorous, territorial', '15–20 years', 'Requires minimum 120 cm vivarium. They need high basking temperatures, UVB, and hiding spots.', 'Low — regular enclosure cleaning, UVB lighting, fresh vegetables daily.', 'Metabolic bone disease, impaction, respiratory infections, tail injuries', 'North Africa, Middle East, India', 'https://images.unsplash.com/photo-1504450874802-0ed58ffa9b64?w=800&q=80', '25–45 cm', '25–45 cm', '0.2–0.9 kg', '0.2–0.9 kg', 'Spiny tail with bright colours — red, yellow, orange, green', true, false)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug, animal_type = EXCLUDED.animal_type, group_name = EXCLUDED.group_name, size = EXCLUDED.size,
  popularity_rank = EXCLUDED.popularity_rank, is_popular = EXCLUDED.is_popular, description = EXCLUDED.description,
  temperament = EXCLUDED.temperament, lifespan = EXCLUDED.lifespan, exercise_needs = EXCLUDED.exercise_needs,
  grooming = EXCLUDED.grooming, health_issues = EXCLUDED.health_issues, origin = EXCLUDED.origin,
  image_url = EXCLUDED.image_url, male_height = EXCLUDED.male_height, female_height = EXCLUDED.female_height,
  male_weight = EXCLUDED.male_weight, female_weight = EXCLUDED.female_weight, coat_type = EXCLUDED.coat_type,
  good_with_children = EXCLUDED.good_with_children, good_with_other_dogs = EXCLUDED.good_with_other_dogs;

-- MORE SMALL PETS
INSERT INTO public.breeds (name, slug, animal_type, group_name, size, popularity_rank, is_popular, description, temperament, lifespan, exercise_needs, grooming, health_issues, origin, image_url, male_height, female_height, male_weight, female_weight, coat_type, good_with_children, good_with_other_dogs)
VALUES
('Rat', 'rat', 'small-pet', 'Rodent', 'small', 68, true, 'Rats are highly intelligent, social rodents that make excellent pets. They can learn tricks, respond to their names, and form deep bonds with their owners.', 'Intelligent, social, affectionate, playful, clean', '2–3 years', 'High — need a large cage and supervised out-of-cage playtime daily. They are active and curious.', 'Low — regular cage cleaning, occasional nail trimming. They self-groom.', 'Respiratory infections (mycoplasma), tumours, obesity, overgrown teeth', 'Worldwide (domesticated from brown rat)', 'https://images.unsplash.com/photo-1585110396063-7a1a12c27714?w=800&q=80', '20–25 cm', '20–25 cm', '0.25–0.5 kg', '0.25–0.5 kg', 'Short fur — white, black, brown, hooded, dumbo', true, true),
('Degu', 'degu', 'small-pet', 'Rodent', 'small', 69, true, 'The Degu is a social, diurnal rodent native to Chile. They are intelligent, vocal, and need companionship. They cannot process sugar and need a specialised diet.', 'Social, vocal, intelligent, active, diurnal', '6–8 years', 'High — need a large multi-level cage and supervised playtime. They are active and social.', 'Moderate — regular cage cleaning, dust baths, nail trimming.', 'Diabetes (sugar sensitivity), dental issues, cataracts, liver disease', 'Chile', 'https://images.unsplash.com/photo-1425082661707-3f5cb3e5e990?w=800&q=80', '25–31 cm', '25–31 cm', '0.17–0.3 kg', '0.17–0.3 kg', 'Brown agouti fur with brush tail', true, true),
('Hedgehog', 'hedgehog', 'small-pet', 'Erinaceid', 'small', 70, true, 'African Pygmy Hedgehogs are small, nocturnal pets known for their spiny coats and cute faces. They are solitary and need gentle handling to build trust.', 'Nocturnal, solitary, shy, curious, defensive (rolls up)', '4–6 years', 'Moderate — need a large enclosure and supervised out-of-cage exploration. They are active at night.', 'Moderate — regular cage cleaning, nail trimming, occasional bathing. They need a heated environment.', 'Wobbly hedgehog syndrome, obesity, respiratory infections, dental issues, mites', 'Africa (domesticated)', 'https://images.unsplash.com/photo-1425082661707-3f5cb3e5e990?w=800&q=80', '13–20 cm', '13–20 cm', '0.2–0.6 kg', '0.2–0.6 kg', 'Spines (quills) with white/brown bands — white, albino, salt and pepper', true, false),
('Gerbil', 'gerbil', 'small-pet', 'Rodent', 'small', 71, true, 'Gerbils are active, social rodents that are fun to watch. They are cleaner than hamsters, rarely bite, and enjoy burrowing in deep substrate.', 'Active, social, curious, friendly, rarely bite', '2–4 years', 'Moderate — need a tank with deep substrate for burrowing. Supervised playtime outside the tank.', 'Low — regular cage cleaning, fresh food and water. They are naturally clean.', 'Respiratory infections, seizures, overgrown teeth, tumours, Tyzzer disease', 'Mongolia (Mongolian gerbil)', 'https://images.unsplash.com/photo-1425082661707-3f5cb3e5e990?w=800&q=80', '10–12 cm', '10–12 cm', '0.05–0.12 kg', '0.05–0.12 kg', 'Agouti, black, white, grey, spotted', true, true),
('Mouse', 'mouse', 'small-pet', 'Rodent', 'small', 72, true, 'Pet mice are small, active, and relatively easy to care for. They are social and should be kept in same-sex groups. Their small size makes them suitable for limited space.', 'Active, social, curious, skittish, nocturnal', '1–3 years', 'Moderate — need a cage with enrichment and supervised playtime. They are very active.', 'Low — regular cage cleaning, fresh food and water.', 'Respiratory infections, tumours, overgrown teeth, mites', 'Worldwide (domesticated from house mouse)', 'https://images.unsplash.com/photo-1425082661707-3f5cb3e5e990?w=800&q=80', '6–10 cm', '6–10 cm', '0.02–0.04 kg', '0.02–0.04 kg', 'Various colours — white, black, brown, agouti', true, true)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug, animal_type = EXCLUDED.animal_type, group_name = EXCLUDED.group_name, size = EXCLUDED.size,
  popularity_rank = EXCLUDED.popularity_rank, is_popular = EXCLUDED.is_popular, description = EXCLUDED.description,
  temperament = EXCLUDED.temperament, lifespan = EXCLUDED.lifespan, exercise_needs = EXCLUDED.exercise_needs,
  grooming = EXCLUDED.grooming, health_issues = EXCLUDED.health_issues, origin = EXCLUDED.origin,
  image_url = EXCLUDED.image_url, male_height = EXCLUDED.male_height, female_height = EXCLUDED.female_height,
  male_weight = EXCLUDED.male_weight, female_weight = EXCLUDED.female_weight, coat_type = EXCLUDED.coat_type,
  good_with_children = EXCLUDED.good_with_children, good_with_other_dogs = EXCLUDED.good_with_other_dogs;
